export const STOCK_CATALOG = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    displayName: '苹果',
    sector: 'Technology',
    region: 'north-america',
    aliases: ['aapl', 'apple', 'apple inc', '苹果', '苹果公司'],
    price: 178.72,
    change: 0.42,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    displayName: '英伟达',
    sector: 'Technology',
    region: 'north-america',
    aliases: ['nvda', 'nvidia', 'nvidia corporation', '英伟达'],
    price: 875.28,
    change: 1.18,
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    displayName: '特斯拉',
    sector: 'Consumer Cyclical',
    region: 'north-america',
    aliases: ['tsla', 'tesla', 'tesla inc', '特斯拉'],
    price: 273.08,
    change: -0.36,
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    displayName: '微软',
    sector: 'Technology',
    region: 'north-america',
    aliases: ['msft', 'microsoft', 'microsoft corporation', '微软'],
    price: 421.44,
    change: 0.28,
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    displayName: '谷歌',
    sector: 'Communication Services',
    region: 'north-america',
    aliases: ['googl', 'google', 'alphabet', 'alphabet inc', '谷歌'],
    price: 152.19,
    change: -0.12,
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    displayName: '摩根大通',
    sector: 'Financial Services',
    region: 'north-america',
    aliases: ['jpm', 'jpmorgan', 'jpmorgan chase', '摩根大通'],
    price: 198.66,
    change: 0.16,
  },
  {
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    displayName: '美国银行',
    sector: 'Financial Services',
    region: 'north-america',
    aliases: ['bac', 'bank of america', '美国银行'],
    price: 36.25,
    change: -0.22,
  },
];

export function toPublicStock(stock) {
  return {
    symbol: stock.symbol,
    name: stock.displayName || stock.name,
    price: stock.price,
    change: stock.change,
    sector: stock.sector,
    region: stock.region,
  };
}
